version: '2.0'
services:
  registry:
    image: registry:2.7
    restart: always
    volumes:
      - registry-data:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml:ro
    networks:
      - registry-ui-net
    container_name: registry

  ui:
    image: joxit/docker-registry-ui:latest
    restart: always
    ports:
      - "80:80"
    environment:
      - REGISTRY_TITLE=Private Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - DELETE_IMAGES=true
      - SINGLE_REGISTRY=true
    container_name: registry-ui
    networks:
      - registry-ui-net
    depends_on:
      - registry
volumes:
    registry-data:
networks:
    registry-ui-net: