version: "3"
services:

  # icloud 同步
  icloudpd:
    image: boredazfcuk/icloudpd:latest
    container_name: icloudpd
    hostname: icloudpd
    restart: always
    entrypoint:
      # 时区
      - TZ=Asia/Shanghai
    volumes:
      # 配置文件夹
      - /share/Container/docker-volumes/icloudpd:/config
      # 媒体目录
      - /share/CACHEDEV2_DATA/Vol2/照片/iCloud:/iCloud
