version: "3"
services:
  # icloud 同步
  icloudpd_01:
    image: boredazfcuk/icloudpd:latest
    container_name: icloudpd_01
    hostname: icloudpd_01
    restart: always
    volumes:
      # 配置文件夹
      - /share/Container/docker-volumes/icloudpd/01:/config
      # 媒体目录
      - /share/CACHEDEV2_DATA/Vol2/照片/iCloud/01:/iCloud
