version: "3.7"
# 服务
services:
  # 影视库 jellyfin
  jellyfin:
    image: nyanmisaka/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000  # 用户id
      - PGID=100   # 用户组id
      - TZ=Asia/Shanghai
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./jellyfin:/config                                      # 配置文件夹
      - /share/Vol1/media_volume/movies:/media_volume/movies    # 电影文件夹
      - /share/Vol1/media_volume/series:/media_volume/series    # 剧集文件夹
      - /share/Vol1/media_volume/bangumi:/media_volume/bangumi  # 番剧文件夹
      - /share/Vol2/media_volume/recordings:/media_volume/recordings # IPTV节目录制
      - /share/Public/bj-unicom-iptv.m3u:/iptv/bj-unicom-iptv.m3u # IPTV视频源
    ports:
      - "8096:8096" # HTTP port
  # nginx
  nginxWebUI:
    image: cym1102/nginxwebui
    container_name: nginxWebUI
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000  # 用户id
      - PGID=100   # 用户组id
      - TZ=Asis/Shanghai
      - BOOT_OPTIONS=--server.port=8866
    privileged: true
    volumes:
      - ./nginxWebUI:/home/nginxWebUI
  # tmm刮削器
  tinymediamanager:
    image: tinymediamanager/tinymediamanager
    container_name: tinymediamanager
    restart: unless-stopped
    volumes:
      - ./tinymediamanager:/data
      - /share/Vol1/media_volume/movies:/media_volume/movies    # 电影文件夹
      - /share/Vol1/media_volume/series:/media_volume/series    # 剧集文件夹
      - /share/Vol1/media_volume/bangumi:/media_volume/bangumi  # 番剧文件夹
    environment:
      - PUID=1000  # 用户id
      - PGID=100   # 用户组id
      - TZ=Asis/Shanghai
    ports:
      - "4000:4000" # HTTP port
  # 自动辅种
  iyuuplus:
    image: iyuucn/iyuuplus
    container_name: iyuuplus
    restart: unless-stopped
    volumes:
      - ./iyuuplus:/IYUU/db
    environment:
      - PUID=1000  # 用户id
      - PGID=100   # 用户组id
      - TZ=Asis/Shanghai
    ports:
      - "8787:8787" # HTTP port




#  emby:
#    image: emby/embyserver:4.6.7.0
#    container_name: emby
#    restart: unless-stopped
#    privileged: true
#    environment:
#      - PUID=1000  # 用户id
#      - PGID=100   # 用户组id
#      - GIDLIST=100
#    devices:
#      - /dev/dri:/dev/dri
#    volumes:
#      # 配置
#      - ./emby:/config
#      # 媒体文件
#      - /share/Vol1/media_volume/movies:/media_volume/movies    # 电影文件夹
#      - /share/Vol1/media_volume/series:/media_volume/series    # 剧集文件夹
#      - /share/Vol1/media_volume/bangumi:/media_volume/bangumi  # 番剧文件夹
#    ports:
#      - "8096:8096" # HTTP port
