version: "3.7"
# 服务
services:
  # 影视库 jellyfin
  jellyfin:
    image: nyanmisaka/jellyfin
    container_name: jellyfin
    restart: always
    environment:
      - TZ=Asia/Shanghai
    devices:
      - /dev/dri:/dev/dri
    volumes:
      # 配置文件夹
      - /share/Container/docker-volumes/jellyfin:/config
      # 威联通的路径完全映射
      - /share:/share
    ports:
      - "8096:8096" # HTTP port
  # nginx
  nginxWebUI:
    image: cym1102/nginxwebui
    container_name: nginxWebUI
    restart: always
    environment:
      - TZ=Asis/Shanghai
      - BOOT_OPTIONS=--server.port=8866
    privileged: true
    volumes:
      - /share/Container/docker-volumes/nginxWebUI:/home/nginxWebUI
    ports:
      # HTTP port
      - "1443:1443"
      - "8866:8866"
  # tmm刮削器
  tinymediamanager:
    image: tinymediamanager/tinymediamanager
    container_name: tinymediamanager
    restart: always
    environment:
      - TZ=Asis/Shanghai
    volumes:
      - /share/Container/docker-volumes/tinymediamanager:/data
      # 威联通的路径完全映射
      - /share:/share
    ports:
      - "4000:4000" # HTTP port
  hlink:
    image: likun7981/hlink # docker镜像名称
    user: "1000:100"
    container_name: hlink
    restart: always
    environment:
      # 指定配置文件位置
      - HLINK_HOME=/share/Container/docker-volumes/hlink
    volumes:
      # 威联通的路径完全映射
      - /share:/share
    ports: # 这个端口映射
      - "9090:9090"