version: "3"
services:
  # 测试下开心不开心
  plex:
    image: amilys/embyserver
    container_name: emby
    hostname: emby
    restart: always
    environment:
      # 用户id
      - PUID=1000
      # 用户组id
      - PGID=100
      - TZ=Asia/Shanghai
    devices:
      - /dev/dri:/dev/dri
    volumes:
      # 配置文件夹
      - /share/Container/docker-volumes/emby/config:/config
      # 媒体目录
      - /share:/share
    ports:
      - "32400:32400"