# 如果openwrt中git clone 不了
# 看看有没有装git,openssh-keygen,openssh-client
# opkg install git openssh-keygen openssh-client
# 以及有没有配置ssh-key
version: "3"
services:
  shadowsocks:
    image: oddrationale/docker-shadowsocks
    command: ["-s", "0.0.0.0", "-p", "${SHADOWSOCKS_PORT}", "-k", "${SHADOWSOCKS_PASSWORD}", "-m", "${SHADOWSOCKS_METHOD}"]
    ports:
      - "${SHADOWSOCKS_PORT}:${SHADOWSOCKS_PORT}"
  nginxWebUI:
    image: cym1102/nginxwebui
    container_name: nginxWebUI
    volumes:
      - "/docker-volumes/nginxWebUI:/home/nginxWebUI"
    environment:
      - BOOT_OPTIONS=--server.port=81
      - TZ=Asia/Shanghai
    ports:
      - "8080:80"