# 如果openwrt中git clone 不了
# 看看有没有装git,openssh-keygen,openssh-client
# opkg install git openssh-keygen openssh-client
# 以及有没有配置ssh-key
version: "3"
services:
  shadowsocks:
    image: oddrationale/docker-shadowsocks
    container_name: shadowsocks
    restart: always
    command: ["-s", "0.0.0.0", "-p", "${SHADOWSOCKS_PORT}", "-k", "${SHADOWSOCKS_PASSWORD}", "-m", "${SHADOWSOCKS_METHOD}"]
    network_mode: bridge
    env_file:
      - .env
    ports:
      - "${SHADOWSOCKS_PORT}:${SHADOWSOCKS_PORT}"
  nginxWebUI:
    image: cym1102/nginxwebui
    container_name: nginxWebUI
    restart: always
    volumes:
      - "/docker-volumes/nginxWebUI:/home/nginxWebUI"
    environment:
      - BOOT_OPTIONS=--server.port=81
      - TZ=Asia/Shanghai
    network_mode: host
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)'