{
 "title": "Speedtest-Exporter Dashboard",
 "description": "Dashboard for Speedtest Exporter https://github.com/MiguelNdeCarvalho/speedtest-exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(speedtest_up, instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(speedtest_up, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Speedtest-Exporter状态",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_up{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "服务ID (最后一次成功)",
   "type": "stat",
   "description": "ServerID of the last test done",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_server_id{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  { "title": "仪表", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "下载速度",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{instance=\"$instance\", job=\"$job\"}*10^-6"
    }
   ]
  },
  {
   "title": "上传速度",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{instance=\"$instance\", job=\"$job\"}*10^-6"
    }
   ]
  },
  {
   "title": "延迟",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "抖动",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_jitter_latency_milliseconds{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  { "title": "图形", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "下载速度 (Mbits/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{instance=\"$instance\", job=\"$job\"}*10^-6>0",
     "legendFormat": "下载速度 (Mbits/s)"
    }
   ]
  },
  {
   "title": "上传速度 (Mbits/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{instance=\"$instance\", job=\"$job\"}*10^-6>0",
     "legendFormat": "上传速度 (Mbits/s)"
    }
   ]
  },
  {
   "title": "延迟与抖动 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "延迟 (ms)"
    },
    {
     "expr": "speedtest_jitter_latency_milliseconds{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "抖动 (ms)"
    }
   ]
  }
 ]
}