version: "3"
services:
  # 核心服务  nas-tools
  nas-tools:
    image: jxxghp/nas-tools
    container_name: nas-tools
    restart: always
    environment:
      - TZ=Asia/Shanghai
      # 用户id
      - PUID=1000
      # 用户组id
      - PGID=100
      # 如需在启动容器时自动升级程程序请设置为true
      - NASTOOL_AUTO_UPDATE=false
      # 掩码权限，默认000，可以考虑设置为022
      - UMASK=022
      # 当你访问github网络很差时，可以考虑解释本注释
      # - REPO_URL=https://ghproxy.com/https://github.com/jxxghp/nas-tools.git
    volumes:
      # 配置文件夹
      - /share/Container/docker-volumes/nas-tools/config:/config
      # 媒体目录
      - /share:/share
    ports:
      - "3000:3000"

  # 索引
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    environment:
      - TZ=Asia/Shanghai
      # 用户id
      - PUID=1000
      # 用户组id
      - PGID=100
      - AUTO_UPDATE=true
    volumes:
      - /share/Container/docker-volumes/jackett/config:/config
      - /share:/share
    ports:
      - "9117:9117"

  # 解决  jackett遇到 CF DDOS的问题
  flaresolverr:
    image: flaresolverr/flaresolverr
    container_name: flaresolverr
    restart: always
    ports:
      - "8191:8191"


  # 媒体库
  jellyfin:
    image: nyanmisaka/jellyfin
    container_name: jellyfin
    restart: always
    environment:
      # 用户id
      - PUID=1000
      # 用户组id
      - PGID=100
      - TZ=Asia/Shanghai
    devices:
      - /dev/dri:/dev/dri
    volumes:
      # 配置文件夹
      - /share/Container/docker-volumes/jellyfin/config:/config
      # 媒体目录
      - /share:/share
    ports:
      - "8096:8096"



  # nginx
  nginxWebUI:
    image: cym1102/nginxwebui
    container_name: nginxWebUI
    restart: always
    environment:
      - TZ=Asis/Shanghai
      - BOOT_OPTIONS=--server.port=8866
    privileged: true
    volumes:
      # 配置文件夹
      - /share/Container/docker-volumes/nginxWebUI:/home/nginxWebUI
    ports:
      # HTTP port
      - "1443:1443"
      - "8866:8866"


  # 下载器
  # 下载器使用macvlan的网络,使得容器获得独立的ip
  # 方便做流量控制
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    networks:
      macvlan:
        ipv4_address: 10.0.0.151
    environment:
      # 用户id
      - PUID=1000
      # 用户组id
      - PGID=100
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080 # QB webui的端口，你可以换成其他端口
    volumes:
      - /docker-volumes/qbittorrent/config:/config
      - /share:/share
    ports:
      - "50126:50126"
      - "50126:50126/udp"
      - "8080:8080"
networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: qvs0
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1