services:
  # 使用macvlan的网络,使得容器获得独立的ip
  # ip范围10.0.0.51~10.0.0.100
  # 方便做流量控制

  # 下载器
  qbittorrent:
    image: linuxserver/qbittorrent:4.4.5
    container_name: qbittorrent
    hostname: qbittorrent
    restart: always
    networks:
      macvlan:
        ipv4_address: 10.0.0.53
    mac_address: 10:00:00:00:00:53
    environment:
      # 用户id
      - PUID=1000
      # 用户组id
      - PGID=100
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080 # QB webui的端口，你可以换成其他端口
    volumes:
      - /vol3/1000/docker-volume/qbittorrent/config:/config
      - /vol1/1000/media_volume:/vol1/1000/media_volume
    ports:
      - "50126:50126"
      - "50126:50126/udp"
      - "8080:8080"

  # IPTV相关
  feiyang_allinone:
    image: youshandefeiyang/allinone
    container_name: feiyang_allinone
    hostname: feiyang_allinone
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      macvlan:
        ipv4_address: 10.0.0.57
    mac_address: 10:00:00:00:00:57
    command: -tv=true -aesKey=${FY_AES_KEY} -userid=${FY_USER_ID} -token=${FY_TOKEN}
    ports:
      - "35455:35455"
    env_file:
      - .env

  # 云盘
  clouddrive:
    image: cloudnas/clouddrive2
    container_name: clouddrive
    hostname: clouddrive
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      macvlan:
        ipv4_address: 10.0.0.58
    mac_address: 10:00:00:00:00:58
    environment:
      - TZ=Asia/Shanghai
      - CLOUDDRIVE_HOME=/Config
    volumes:
      - /vol1/1000/media_volume:/vol1/1000/media_volume:shared
      - /vol3/1000/docker-volume/clouddrive/config:/Config
    privileged: true
    devices:
      - /dev/fuse:/dev/fuse
    ports:
      - "19798:19798"

# 需要提前手动创建这个网络
# docker network create --driver macvlan --subnet 10.0.0.0/24 --gateway 10.0.0.1 --opt parent=eno1 macvlan
networks:
  macvlan:
    external: true
    name: macvlan