services:
  # 使用macvlan的网络,使得容器获得独立的ip
  # ip范围10.0.0.51~10.0.0.100
  # 方便做流量控制
#  moviepilot-v2
  moviepilot-v2:
    image: jxxghp/moviepilot-v2:latest
    container_name: moviepilot-v2
    hostname: moviepilot-v2
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - qbittorrent
      - plex
      - clouddrive
    networks:
      macvlan:
        ipv4_address: 10.0.0.51
    mac_address: 10:00:00:00:00:51
    environment:
      # 时区
      - TZ=Asia/Shanghai
      # WEB服务端口，默认3000，可自行修改，不能与API服务端口冲突
      - NGINX_PORT=3000
      # API服务端口，默认3001，可自行修改，不能与WEB服务端口冲突
      - PORT=3001
      # 用户id
      - PUID=1000
      # 用户组id
      - PGID=100
      # 掩码权限，默认000，可以考虑设置为022
      - UMASK=022
      # 管理用户id
      - SUPERUSER=sowevo
    ports:
      - "3000:3000"
    volumes:
      # 配置文件夹
      - /vol3/1000/docker-volume/moviepilot/config:/config
      - /vol3/1000/docker-volume/moviepilot/core:/moviepilot/.cache/ms-playwright
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # 媒体目录
      - /vol1/1000/media_volume:/vol1/1000/media_volume
  plex:
    image: linuxserver/plex
    container_name: plex
    hostname: plex
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      macvlan:
        ipv4_address: 10.0.0.61
    mac_address: 10:00:00:00:00:61
    environment:
      # 用户id
      - PUID=1000
      # 用户组id
      - PGID=100
      - TZ=Asia/Shanghai
      - VERSION=docker
    devices:
      - /dev/dri:/dev/dri
    volumes:
      # 配置文件夹
      - /vol3/1000/docker-volume/plex/config:/config
      # 媒体目录
      - /vol1/1000/media_volume:/vol1/1000/media_volume
    ports:
      - "32400:32400"

  # 下载器
  qbittorrent:
    image: linuxserver/qbittorrent:4.4.5
    container_name: qbittorrent
    hostname: qbittorrent
    restart: always
    networks:
      macvlan:
        ipv4_address: 10.0.0.53
    mac_address: 10:00:00:00:00:53
    environment:
      # 用户id
      - PUID=1000
      # 用户组id
      - PGID=100
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080 # QB webui的端口，你可以换成其他端口
    volumes:
      - /vol3/1000/docker-volume/qbittorrent/config:/config
      # 媒体目录
      - /vol1/1000/media_volume:/vol1/1000/media_volume
    ports:
      - "50126:50126"
      - "50126:50126/udp"
      - "8080:8080"

  # IPTV相关
  feiyang_allinone:
    image: youshandefeiyang/allinone
    container_name: feiyang_allinone
    hostname: feiyang_allinone
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      macvlan:
        ipv4_address: 10.0.0.57
    mac_address: 10:00:00:00:00:57
    command: -tv=true -aesKey=${FY_AES_KEY} -userid=${FY_USER_ID} -token=${FY_TOKEN}
    ports:
      - "35455:35455"
    env_file:
      - .env

  # 云盘
  clouddrive:
    image: cloudnas/clouddrive2
    container_name: clouddrive
    hostname: clouddrive
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      macvlan:
        ipv4_address: 10.0.0.58
    mac_address: 10:00:00:00:00:58
    environment:
      - TZ=Asia/Shanghai
      - CLOUDDRIVE_HOME=/Config
    volumes:
      # 媒体目录
      - /vol1/1000/media_volume:/vol1/1000/media_volume:shared
      - /vol3/1000/docker-volume/clouddrive/config:/Config
    privileged: true
    devices:
      - /dev/fuse:/dev/fuse
    ports:
      - "19798:19798"




# 需要提前手动创建这个网络
# docker network create --driver macvlan --subnet 10.0.0.0/24 --gateway 10.0.0.1 --opt parent=eno1 macvlan
networks:
  macvlan:
    external: true
    name: macvlan