global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
#  - job_name: cadvisor
#    scrape_interval: 5s
#    static_configs:
#      - targets:
#          - cadvisor:8080
#  - job_name: speedtest-exporter
#    scrape_interval: 30m
#    scrape_timeout: 1m
#    static_configs:
#      - targets:
#          - speedtest-exporter:9798
  - job_name: 'iperf3'
    metrics_path: /probe
    static_configs:
      - targets:
          - 10.0.0.5
    params:
      port: [ '5201' ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: 10.0.0.100:9579