global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: speedtest-exporter
    scrape_interval: 30m
    scrape_timeout: 1m
    static_configs:
      - targets:
          - speedtest-exporter:9798