services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    ports:
      - "8123:8123"
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${HOME}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
