version: "3"
services:
  # homeassistant
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    hostname: homeassistant
    restart: always
    networks:
      macvlan2:
        ipv4_address: 10.0.0.161
    volumes:
      # 配置文件夹
      - /share/Container/docker-volumes/homeassistant/config:/config
    ports:
      - "8123:8123"

networks:
  macvlan2:
    driver: macvlan
    driver_opts:
      parent: qvs0
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1